export { default as OnBoarding, assets as OnBoardingAssets } from "./OnBoarding"
export { default as Login } from "./Login"
export { default as ForgotPassword } from "./ForgotPassword"
export { default as ResetPasswordSuccessfully } from "./ResetPasswordSuccessfully"
export { default as SignUp } from "./SignUp"
export { default as SignUpSuccessfully } from "./SignUpSuccessfully"
